on: [push, pull_request]

name: CI / GitHub Actions

jobs:
  installDependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: 'npm ci'
    - name: Run build
      env:
        NODE_OPTIONS: --max_old_space_size=4096
      run: 'npm run build'
    # FIXME(HashimotoYT)
    # - name: Run tests
    #   env:
    #     NODE_OPTIONS: --max_old_space_size=4096
    #   run: 'npm test'
    - name: Publish via semantic-release
      if: github['ref'] == 'refs/heads/master'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run semantic-release
