on:
  schedule:
    - cron: 00 09 * * *
  workflow_dispatch: {}

name: Auto-merge Crowdin PR

jobs:
  installDependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Automerge PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run automerge
