on:
  schedule:
    - cron: 0 */1 * * *

name: Fetch translated content

jobs:
  fetchTranslatedContent:
    name: Fetch latest translated content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Download content from Crowdin
        uses: crowdin/github-action@1.0.9
        with:
          download_translations: true
          localization_branch_name: new-translations
          config: '/crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
